### ISSUE TITLE
Regarding Native library .so in Eclipse.

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-androidx-cardview#1]
Hello Dandar3,
In one of my project, i have to use .so native library. But i didn't load. I put .so library in libs & jni & jniLibs folder but it didn't load. But if i use without converting project to androidx, it's work fine. So, ultimately eclipse didn't support native library in androidx. If you have any knowledge about this or if you know how to load native library .so in eclipse then it would be appreciate. Thank you for your 24*7 support.

**Comment by dandar3** [comment]
@vijaybhairavjibhaiaslaliya 
That is strange alright, I wouldn't see any relation between a custom Java libraries (which AndroidX really are) and the system `System.loadLibrary()` behaviour.

I have't used native libraries, but I understand for Eclipse they should be put in `libs\CPU_API` folders
https://stackoverflow.com/a/27523384/308836

I will try to write a very simple app with some native function to try it, which AndroidX libraries do you use in your app?

**Comment by vijaybhairavjibhaiaslaliya** [comment]
thanks for your support and if i have any query i have inform you.....
